const {EmbedBuilder, SlashCommandBuilder, MessageFlags} = require('discord.js');
module.exports = {
  data: new SlashCommandBuilder()
    .setName('wheel')
    .setDescription('Spin the wheel to get a random plant or zombie deck')
    .addIntegerOption(
        option => option
            .setName('number')
            .setDescription('Number of cards to put in deck')
            .setRequired(true)
            .setMinValue(1)
            .setMaxValue(40)
    )
    .addStringOption(
         option => option.setName('hero').setDescription('The hero of the wheel deck').addChoices(
        { name: "Captain Combustible", value: "Captain Combustible"},
        { name: "Chompzilla", value: "Chompzilla"}, 
        { name: "Citron/BC", value: "Citron/BC"}, 
        {name: "Grass Knuckles", value: "Grass Knuckles"}, 
        {name: "Green Shadow", value: "Green Shadow"},
        {name: "Night Cap", value: "Night Cap"},
        {name: "Rose", value: "Rose"},
        {name: "Solar Flare", value: "Solar Flare"},
        {name: "Spudow", value: "Spudow"}, 
        {name: "Wall Knight", value: "Wall Knight"}, 
        {name: "Brain Freeze", value: "Brain Freeze"}, 
        {name: "Electric Boogaloo", value: "Electric Boogaloo"},
        {name: "Huge Giganticus/SB", value: "Huge Giganticus/SB"},
        {name: "Impfinity", value: "Impfinity"}, 
        {name: "Immorticia", value: "Immorticia"}, 
        {name: "Neptuna", value: "Neptuna"}, 
        {name: "Rustbolt", value: "Rustbolt"}, 
        {name: "Professor Brainstorm", value: "Professor Brainstorm"}, 
        {name: "Smash", value: "Smash"}, 
        {name: "Zmech", value: "Zmech"},
      ).setRequired(true)),
      async execute(interaction) {
        const number = interaction.options.getInteger('number');
        const hero = interaction.options.getString('hero');
          const gurdianWords = [
          "Small-Nut",
          "Sting Bean",
          "Wall-Nut",
          "Pismashio",
          "Spineapple",
          "Potato Mine",
          "Cactus",
          "Gardening Gloves",
          "Sea-Shroom",
          "Water Chestnut",
          "Pea-Nut",
          "Steel Magnolia",
          "Photosynthesizer",
          "Spikeweed Sector",
          "Plantern",
          "Grape Responsibility",
          "Primal Potato Mine",
          "Grizzly Pear",
          "Grave Buster",
          "Hibernating Beary",
          "Prickly Pear",
          "Smackadamia",
          "Tough Beets",
          "Cosmic Nut",
          "Starch-Lord",
          "Blockbuster",
          "Pumpkin Shell",
          "Jugger-Nut",
          "Mirror-Nut",
          "Guacodile",
          "Doom-Shroom",
          "Galacta-Cactus",
          "Force Field",
          "Gravitree",
          "Three-Nut",
          "Marine Bean",
          "Primal Wall-Nut",
          "Poppin' Poppies",
          "Soul Patch",
          "Wall-Nut Bowling",
          "Body-Gourd",
          "Pecanolith",
          "Tricarrotops",
          "Loco Coco",
          "Forget-Me-Nuts",
          "Garlic",
          "Corn Dog",
          "Hot Date",
          "Health-Nut",
          "Pear Cub",
          "Shamrocket",
          "Red Stinger",
        ];
        const smartyWords = [
          "Snowdrop",
          "Weenie Beanie",
          "Snow Pea",
          "Cattail",
          "Smoosh-Shroom",
          "Threepeater",
          "Iceberg Lettuce",
          "Shellery",
          "Rescue Radish",
          "Spring Bean",
          "Vanilla",
          "Carrotillery",
          "Mars Flytrap",
          "Planet of the Grapes",
          "Leaf Blower",
          "Grave Mistake",
          "Pear Pal",
          "Primal Peashooter",
          "Admiral Navy Bean",
          "Lightning Reed",
          "Chilly Pepper",
          "Navy Bean",
          "Jumping Bean",
          "Cosmic Bean",
          "Melon-Pult",
          "Tricorn",
          "Lily Pad",
          "Sow Magic Beans",
          "Bean Counter",
          "Snapdragon",
          "Winter Squash",
          "Laser Cattail",
          "Bog of Enlightenment",
          "Cool Bean",
          "Jelly Bean",
          "Rotobaga",
          "Shrinking Violet",
          "Brainana",
          "Winter Melon",
          "The Great Zucchini",
          "Shooting Starfruit",
          "Dark Matter Dragonfruit",
          "Lima-Pleurodon",
          "Bird of Paradise",
          "Spyris",
          "Go-Nuts",
          "Mayflower",
          "Sportacus",
          "Snake Grass",
          "Witch Hazel",
          "Jolly Holly",
          "Sap-Fling",
        ];
        const kabloomWords = [
          "Button Mushroom",
          "Berry Blast",
          "Buff-Shroom",
          "Seedling",
          "Zapricot",
          "Poison Mushroom",
          "Berry Angry",
          "Mushroom Ringleader",
          "Poison Ivy",
          "Pair of Pears",
          "Bluesberry",
          "Sizzle",
          "Banana Bomb",
          "Mushroom Grotto",
          "Invasive Species",
          "Puff-Shroom",
          "Veloci-Radish Hatchling",
          "Hot Lava",
          "Shroom for Two",
          "Wild Berry",
          "Petal-Morphosis",
          "Sour Grapes",
          "Poison Oak",
          "Cosmic Mushroom",
          "Lava Guava",
          "Cro-Magnolia",
          "Shelf Mushroom",
          "Punish-Shroom",
          "Sergeant Strongberry",
          "Cherry Bomb",
          "Grapes of Wrath",
          "Astro-Shroom",
          "Banana Launcher",
          "Pair Pearadise",
          "Fireweed",
          "Imitater",
          "Strawberrian",
          "Pineclone",
          "Dandy Lion King",
          "Kernel Corn",
          "Reincarnation",
          "Molekale",
          "Gloom-Shroom",
          "Veloci-Radish Hunter",
          "Blooming Heart",
          "High-Voltage Currant",
          "Sonic Bloom",
          "Transfiguration",
          "Atomic Bombegranate",
          "Electric Blueberry",
        ];
        const megaGrowWords = [
          "Peashooter",
          "Torchwood",
          "Cabbage-Pult",
          "Fertilize",
          "Flourish",
          "Grow-Shroom",
          "Repeater",
          "Bonk Choy",
          "Pea Pod",
          "Sweet Potato",
          "Fire Peashooter",
          "Skyshooter",
          "Coffee Grounds",
          "Sweet Pea",
          "Vegetation Mutation",
          "Umbrella Leaf",
          "Half-Banana",
          "Typical Beanstalk",
          "The Podfather",
          "Plant Food",
          "Re-Peat Moss",
          "Whipvine",
          "Super-Phat Beets",
          "Banana Peel",
          "Cosmic Pea",
          "Bamboozle",
          "Pea Patch",
          "Party Thyme",
          "Black-Eyed Pea",
          "Potted Powerhouse",
          "Espresso Fiesta",
          "Moonbean",
          "Pod Fighter",
          "The Red Plant-It",
          "Split Pea",
          "Grape Power",
          "Savage Spinach",
          "Doubled Mint",
          "Muscle Sprout",
          "Bananasaurus Rex",
          "Captain Cucumber",
          "Onion Rings",
          "Gatling Pea",
          "Apotatosaurus",
          "Clique Peas",
          "Lily of the Valley",
          "Banana Split",
          "Plucky Clover",
        ];
        const solarWords = [
          "Bellflower",
          "Sunflower",
          "Mixed Nuts",
          "Squash",
          "Smashing Pumpkin",
          "Morning Glory",
          "Fume-Shroom",
          "Pepper M.D.",
          "Water Balloons",
          "Venus Flytrap",
          "Bloomerang",
          "Metal Petal Sunflower",
          "Cosmoss",
          "Apple-Saucer",
          "Venus Flytraplanet",
          "Kernel-Pult",
          "Lil' Buddy",
          "Sunnier-Shroom",
          "Sage Sage",
          "Whack-a-Zombie",
          "Lawnmower",
          "Magnifying Grass",
          "Power Flower",
          "Cosmic Flower",
          "Heartichoke",
          "Elderberry",
          "Eyespore",
          "Twin Sunflower",
          "2nd-Best Taco of All Time",
          "Chomper",
          "Laser Bean",
          "Solar Winds",
          "Wing-Nut",
          "Tactical Cuke",
          "Primal Sunflower",
          "Sunflower Seed",
          "Sun Strike",
          "Briar Rose",
          "Three-Headed Chomper",
          "Cornucopia",
          "Astrocado",
          "Astro Vera",
          "Cob Cannon",
          "Aloesaurus",
          "Haunted Pumpking",
          "Sun-Shroom",
          "Jack O' Lantern",
          "Ketchup Mechanic",
          "Toadstool",
        ];
        const sneakyWords = [
          "Imp",
          "Mini-Ninja",
          "Smoke Bomb",
          "Fishy Imp",
          "Smelly Zombie",
          "Headstone Carver",
          "Zombie Chicken",
          "Hot Dog Imp",
          "Swashbuckler Zombie",
          "Backyard Bounce",
          "Stealthy Imp",
          "Firefighter",
          "Graveyard",
          "Ice Pirate",
          "Frosty Mustache",
          "Swabbie",
          "Barrel of Barrels",
          "Monkey Smuggler",
          "Imp Commander",
          "Barrel Roller Zombie",
          "Surprise Gargantuar",
          "Walrus Rider",
          "Zombot Stomp",
          "Cosmic Imp",
          "Space Pirate",
          "Blowgun Imp",
          "Buried Treasure",
          "Toxic Waste Imp",
          "Line Dancing Zombie",
          "Pogo Bouncer",
          "Tomb Raiser Zombie",
          "Ducky Tube Zombie",
          "Dr. Spacetime",
          "Laser Base Alpha",
          "Cursed Gargolith",
          "Excavator Zombie",
          "Unthawed Viking",
          "Mixed-Up Gravedigger",
          "Zombot Sharktronic Sub",
          "Zombot Plank Walker",
          "Space Cowboy",
          "Cryo-Yeti",
          "Zombot Aerostatic Gondola",
          "Raiding Raptor",
          "Imposter",
          "Fire Rooster",
          "Imp-Throwing Imp",
          "Captain Flameface",
          "Zombie High Diver",
          "Trapper Zombie",
        ];
        const beastlyWords = [
          "Skunk Punk",
          "Pied Piper",
          "Zookeeper",
          "Dolphin Rider",
          "Locust Swarm",
          "Dog Walker",
          "Nibble",
          "Snorkel Zombie",
          "Yeti Lunchbox",
          "Haunting Zombie",
          "Loudmouth",
          "B-flat",
          "Total Eclipse",
          "Alien Ooze",
          "Surfer Zombie",
          "Haunting Ghost",
          "Goat",
          "Vengeful Cyborg",
          "Squirrel Herder",
          "Vimpire",
          "Vitamin Z",
          "Kangaroo Rider",
          "Smashing Gargantuar",
          "Biodome Botanist",
          "Cosmic Yeti",
          "Primordial Cheese Shover",
          "Killer Whale",
          "Cat Lady",
          "Zombie Yeti",
          "Deep Sea Gargantuar",
          "Maniacal Laugh",
          "Cheese Cutter",
          "Cyborg Zombie",
          "Area 22",
          "Extinction Event",
          "Ancient Vimpire",
          "Hunting Grounds",
          "Nurse Gargantuar",
          "Octo Zombie",
          "Zombot 1000",
          "Interstellar Bounty Hunter",
          "Supernova Gargantuar",
          "Mondo Bronto",
          "Gargantuar-Throwing Gargantuar",
          "Fraidy Cat",
          "Secret Agent",
          "Energy Drink Zombie",
          "Synchronized Swimmer",
          "Hover-Goat 3000",
          "Overstuffed Zombie",
          "Sneezing Zombie",
          "King of the Grill",
        ];
        const crazyWords = [
          "Backup Dancer",
          "Bungee Plumber",
          "Cuckoo Zombie",
          "Disco Zombie",
          "Flamenco Zombie",
          "Tennis Champ",
          "Unlife of the Party",
          "Conga Zombie",
          "Newspaper Zombie",
          "Cakesplosion",
          "Orchestra Conductor",
          "Foot Soldier Zombie",
          "Loose Cannon",
          "Meteor Z",
          "Space Ninja",
          "Mystery Egg",
          "Sugary Treat",
          "Trapper Territory",
          "Exploding Imp",
          "Jester",
          "Zombot's Wrath",
          "The Chickening",
          "Imp-Throwing Gargantuar",
          "Final Mission",
          "Cosmic Dancer",
          "Gizzard Lizard",
          "Disco Dance Floor",
          "Aerobics Instructor",
          "Abracadaver",
          "Fireworks Zombie",
          "Disco-Tron 3000",
          "Disco-Naut",
          "Moon Base Z",
          "Gas Giant",
          "Quickdraw Con Man",
          "Grave Robber",
          "Zombie's Best Friend",
          "Barrel of Deadbeards",
          "Valkyrie",
          "Gargantuars' Feast",
          "Quasar Wizard",
          "Binary Stars",
          "Tankylosaurus",
          "Headhunter",
          "Exploding Fruitcake",
          "Unexpected Gifts",
          "Stupid Cupid",
          "Frankentuar",
          "Gargantuar-Throwing Imp",
          "Hippity Hop Gargantuar",
        ];
        const brainyWords = [
          "Cardboard Robot Zombie",
          "Paparazzi Zombie",
          "Lurch for Lunch",
          "Fun-Dead Raiser",
          "Drum Major",
          "Chimney Sweep",
          "Beam Me Up",
          "Cell Phone Zombie",
          "Pool Shark",
          "Zombot Drone Engineer",
          "Brain Vendor",
          "Mountain Climber",
          "Cryo-Brain",
          "Medulla Nebula",
          "Moonwalker",
          "Copter Commando",
          "Mustache Waxer",
          "Pirate's Booty",
          "Gentleman Zombie",
          "Kite Flyer",
          "Gadget Scientist",
          "Hail-a-Copter",
          "Wizard Gargantuar",
          "Cosmic Scientist",
          "Triplication",
          "Zom-Blob",
          "Mustache Monument",
          "Electrician",
          "Rocket Science",
          "Mad Chemist",
          "Portal Technician",
          "Neutron Imp",
          "Transformation Station",
          "Wormhole Gatekeeper",
          "Evolutionary Leap",
          "Parasol Zombie",
          "Duckstache",
          "Teleport",
          "Shieldcrusher Viking",
          "Trickster",
          "Interdimensional Zombie",
          "Teleportation Zombie",
          "Gargantuar Mime",
          "Zombot Dinotronic Mechasaur",
          "Leprechaun Imp",
          "Regifting Zombie",
          "Trick-or-Treater",
          "Thinking Cap",
          "Kitchen Sink Zombie",
          "Bad Moon Rising",
        ];
        const heartyWords = [
          "Baseball Zombie",
          "Rolling Stone",
          "Conehead",
          "Team Mascot",
          "Medic",
          "Arm Wrestler",
          "Camel Crossing",
          "Flag Zombie",
          "Terrify",
          "Trash Can Zombie",
          "Buckethead",
          "Ra Zombie",
          "Cone Zone",
          "Celestial Custodian",
          "Screen Door Zombie",
          "Healthy Treat",
          "Zombie Middle Manager",
          "Leftovers",
          "Sumo Wrestler",
          "Zombie Coach",
          "Monster Mash",
          "Knight of the Living Dead",
          "Rodeo Gargantuar",
          "Escape through Time",
          "Cosmic Sports Star",
          "Primeval Yeti",
          "Lost Colosseum",
          "Landscaper",
          "Weed Spray",
          "All-Star Zombie",
          "Coffee Zombie",
          "Black Hole",
          "Genetic Experiment",
          "Planetary Gladiator",
          "Jurassic Fossilhead",
          "Knockout",
          "Turquoise Skull Zombie",
          "Zombie King",
          "Undying Pharaoh",
          "Wannabe hero",
          "Intergalactic Warlord",
          "Zombot Battlecruiser 5000",
          "Stompadon",
          "Chum Champion",
          "Zombology Teacher",
          "Gargologist",
          "Turkey Rider",
          "Going Viral",
          "Bonus Track Buckethead",
          "Defensive End",
        ];
        const heroWordsMap = {
          // Beta Carrotina
          "Citron/BC": gurdianWords.concat(smartyWords),
          // Captain Combustible
          "Captain Combustible": kabloomWords.concat(megaGrowWords),
          // Chompzilla
          "Chompzilla": megaGrowWords.concat(solarWords),
          // Grass Knuckles
          "Grass Knuckles": gurdianWords.concat(megaGrowWords),
          // Green Shadow
          "Green Shadow": megaGrowWords.concat(smartyWords),
          // Nightcap
          "Night Cap": kabloomWords.concat(smartyWords),
          // Rose
          "Rose": smartyWords.concat(solarWords),
          // Solar Flare
          "Solar Flare": kabloomWords.concat(solarWords),
          // Spudow
          "Spudow": kabloomWords.concat(gurdianWords),
          // Wall-Knight
          "Wall Knight": gurdianWords.concat(solarWords),
          // Brain Freeze
          "Brain Freeze": sneakyWords.concat(beastlyWords),
          // Electric Boogaloo
          "Electric Boogaloo": beastlyWords.concat(crazyWords),
          // Huge-Gigantacus
          "Huge Gigantacus/SB": sneakyWords.concat(brainyWords),
          // Impfinity
        "Impfinity": sneakyWords.concat(crazyWords),
          // Immorticia
          "Immorticia": beastlyWords.concat(brainyWords),
          // Neptuna
          "Neptuna": sneakyWords.concat(heartyWords),
          // Professor Brainstorm
          "Professor Brainstorm": crazyWords.concat(brainyWords),
          // Rustbolt
          "Rustbolt": brainyWords.concat(heartyWords),
          // The Smash
          "Smash": beastlyWords.concat(heartyWords),
          // Z-Mech
          "Zmech": heartyWords.concat(crazyWords),
    };
        const wordsArray = heroWordsMap[hero];
        const randomWords = [];
                const remainingWords = [...wordsArray];
                for (let i = 0; i < number; i++) {
                  const randomIndex = Math.floor(Math.random() * remainingWords.length);
                  const selectedWord = remainingWords.splice(randomIndex, 1)[0];
                  randomWords.push(selectedWord);
                }
        
                // Create and send the embed
                const embed = new EmbedBuilder()
                  .setTitle(
                    `Wheel ${
                      hero.charAt(0).toUpperCase() + hero.slice(1)
                    } Deck`
                  )
                  .setDescription(
                    `Here is your wheel deck for ${hero}:\n**${randomWords.join(
                      "\n"
                    )}**`
                  )
                  .setColor("Random");
        
                await interaction.reply({
                  embeds: [embed]
                });
      }
}
